<?php
/******************************************
French
Admin Category Language
******************************************/

$lang['categories']					= 'catégories';
$lang['error_must_select']			= "Vous devez sélectionner une catégorie d'organiser";
$lang['error_not_found']			= "La catégorie demandée n'a pas pu être trouvé.";
$lang['organize_category']			= 'Organiser "% S" Catégorie';
$lang['organize']					= 'organiser';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Catégorie formulaire';
$lang['name']						= 'nom';
$lang['slug']						= 'Slug';
$lang['description']				= 'Description';
$lang['excerpt']					= 'extrait';
$lang['sequence']					= 'séquence';
$lang['image']						= 'image';
$lang['seo_title']					= 'Titre SEO';
$lang['meta']						= 'métadonnées';
$lang['message_category_saved']		= 'La catégorie a été enregistré!';
$lang['error_file_upload']			= "<p> vous n'avez pas sélectionné un fichier à télécharger. </ p>"; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'La catégorie a été supprimée.';
$lang['current_file']				= 'fichier actuel';
$lang['confirm_delete_category']	= 'Etes-vous sûr de vouloir effacer cette catégorie?';
$lang['add_new_category']			= 'Ajouter une nouvelle catégorie';
$lang['no_categories']				= "Il n'y a pas de catégories";
$lang['attributes']					= 'attributs';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= "Glissez et déposez les produits dans l'ordre que vous souhaitez qu'ils apparaissent.";
$lang['sku']						= 'SKU';
$lang['price']						= 'prix';
$lang['sale']						= 'vente';
$lang['max_file_size']				= 'Taille maximale du fichier';

$lang['Likes']						= 'aime';
$lang['Seller']						= 'vendeur';
$lang['Buy Now']						= 'Acheter maintenant';
$lang['Subcategories']					= 'sous-catégories';
$lang['Other Categories']				= 'autres catégories';
$lang['Last Added']						= 'Dernier ajout';
$lang['Most Viewed']						= 'Les plus vues';
$lang['Zero Downloads']						= 'zéro Téléchargement';
$lang['Populairty']						= 'Populairty';

$lang['Successfull Added to your Wishlist']						= 'Successfull ajouté à vos favoris';


