<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']					= '分类';
$lang['error_must_select']			= '你必须选择一个类别来组织';
$lang['error_not_found']			= '所请求的类不能被找到.';
$lang['organize_category']			= '举办​​“％s的”类别';
$lang['organize']					= '组织';
$lang['category_id']				= 'ID';
$lang['category_form']				= '分类表';
$lang['name']						= '名称';
$lang['slug']						= '金属块';
$lang['description']				= '描述';
$lang['excerpt']					= '摘抄';
$lang['sequence']					= '序列';
$lang['image']						= '图像';
$lang['seo_title']					= '搜索引擎优化标题';
$lang['meta']						= '元数据';
$lang['message_category_saved']		= '该类别的已保存!';
$lang['error_file_upload']			= '<p>您没有选择要上传的文件.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= '该类别已被删除.';
$lang['current_file']				= '当前文件';
$lang['confirm_delete_category']	= '您确定要删除这个类别?';
$lang['add_new_category']			= '添加新类别';
$lang['no_categories']				= '目前没有任何分类';
$lang['attributes']					= '属性';
$lang['seo']						= '搜索引擎优化';
$lang['parent']						= '亲';
$lang['meta_data_description']		= '恩。<meta name="description" content="We销售产品，帮助you"/>;';
$lang['drag_and_drop']				= '拖放产品的订单，您希望他们出现.';
$lang['sku']						= 'SKU';
$lang['price']						= '价格';
$lang['sale']						= '卖';
$lang['max_file_size']				= '最大文件大小';

$lang['Likes']						= '喜欢';
$lang['Seller']						= '卖家';
$lang['Buy Now']						= '现在购买';
$lang['Subcategories']					= '小类';
$lang['Other Categories']				= '其他分类';
$lang['Last Added']						= '最新添加';
$lang['Most Viewed']						= '最受欢迎';
$lang['Zero Downloads']						= '零下载';
$lang['Populairty']						= '声望';

$lang['Successfull Added to your Wishlist']						= '全成添加到您的收藏';


